// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.daiyida.api.domain.resource;

import com.daiyida.api.domain.resource.Resource;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Resource_Roo_Configurable {
    
    declare @type: Resource: @Configurable;
    
}
