// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.daiyida.api.domain.bankcard;

import com.daiyida.api.domain.bankcard.BankCard;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect BankCard_Roo_Configurable {
    
    declare @type: BankCard: @Configurable;
    
}
